### ISSUE TITLE
GOSW5-Contact us section

### ISSUE THREAD

**Issue by 07souravkunda** [GameofSource-GFG/Web-Development#10]
GeeksforGeeks student chapter contact us section. Create it as a separate component and make a contact us form with name, email, phone number and message to the student chapter.

**Comment by somashrirastogi** [comment]
Please assign this to me

**Comment by sachinsom93** [comment]
Assign me this please

**Comment by Shreya-art** [comment]
can you assign it to me??

**Comment by lakshaybomotra** [comment]
Assign it to me

**Comment by Shrayanshi** [comment]
Please assign it to me!

**Comment by 07souravkunda** [comment]
@somashrirastogi go for it!

**Comment by somashrirastogi** [comment]
ok thanks @07souravkunda

**Comment by Tejaswika** [comment]
assign it to mee

**Comment by Priyanshu-official** [comment]
@somashrirastogi  Have you done this!
if not let me know I will work on this or If need help let me know
@07souravkunda

**Comment by deepak-mahajan-dev** [comment]
I can create responsive UI contact form.

**Comment by geekyaditya100** [comment]
@somashrirastogi thank you for the contribution. You have recieved 10 points. Keep it up
