### ISSUE TITLE
GOSW6-Student chapter Google map coordinates at contact us

### ISSUE THREAD

**Issue by 07souravkunda** [GameofSource-GFG/Web-Development#11]
Geeks for geeks student chapter gmap should be added to the contact us form.

**Comment by lakshaybomotra** [comment]
Assign me this

**Comment by iampavangandhi** [comment]
I want to try this

**Comment by 07souravkunda** [comment]
@lakshayb121 go for it!

**Comment by abhinavmaharana** [comment]
Assign me please i will do this

**Comment by Tejaswika** [comment]
assign it to mee

**Comment by ashish11chawda** [comment]
@lakshayb121 Buddy, any update on your work till now?
If you couldn't update us till 16:00 IST today, I'll have to unassign you from this issue.

**Comment by Harshal0902** [comment]
@pixan198 if @lakshayb121 is not working on this issue, can you please assign this to me?

**Comment by Harshal0902** [comment]
@pixan198 , please assign this task to me

**Comment by lakshaybomotra** [comment]
> @pixan198 if @lakshayb121 is not working on this issue, can you please assign this to me?

Yes @pixan198 i am not able to work because of some family problem please assign this to him.

**Comment by ashish11chawda** [comment]
@lakshayb121 
No worries, take another issue when you're free
Thanks for the update!

@Harshal0902 You can start working on this!

I've an idea see if you like it!
Design a component so that someone can pass the Google location as a prop and your component will render the location on webpage

**Comment by Harshal0902** [comment]
@pixan198 Thank you, It would be better if you can share the correct coordinates for Student Chapter.

**Comment by ashish11chawda** [comment]
@Harshal0902 you can use any dummy location for now!

**Comment by geekyaditya100** [comment]
@Harshal0902 thank you for the contribution and we are extremely sorry for the late closing of this issue. YOu have receieved 10 points for the submisison.
