### ISSUE TITLE
GOSW7-Social Media Links

### ISSUE THREAD

**Issue by 07souravkunda** [GameofSource-GFG/Web-Development#12]
Add social media icons to the site at the react side html. These icons must be displayed in each and every component rendered. Set a correct position.

**Comment by somashrirastogi** [comment]
assign please

**Comment by sachinsom93** [comment]
Assign me plz

**Comment by vaibhavarora102** [comment]
hi Can you pls assign me
@07souravkunda

**Comment by Shrayanshi** [comment]
Please assign it to me!

**Comment by 07souravkunda** [comment]
Okay @Shrayanshi , Work on this issue.

**Comment by vaibhavarora102** [comment]
@07souravkunda  I guess it on first come first serve basis
Isn't it?

**Comment by 07souravkunda** [comment]
@vaibhavarora102 Yeah but you are assigned to another issue. You can work on other issues after your PR is successfully merged for current issue.

**Comment by Tejaswika** [comment]
assign it to mee

**Comment by Brighu-Raina** [comment]
assign it to me

**Comment by sumanthgunda** [comment]
assign it to me

**Comment by shivarajloni** [comment]
hey! can i contribute

**Comment by ashish11chawda** [comment]
Hey, @Shrayanshi 
Any update on your work till now?
If you couldn't update us till 16:00 IST today, I'll have to unassign you from this issue.

**Comment by sachinsom93** [comment]
@pixan198 could you assign me this please, if @Shrayanshi is not working on this

**Comment by sachinsom93** [comment]
Can I work on this ?

**Comment by ashish11chawda** [comment]
@sachinsom93 Please start working on it!

**Comment by sachinsom93** [comment]
@pixan198 please review my PR for issue GOSW9
