### ISSUE TITLE
GOSW8-Timeline UI in home page

### ISSUE THREAD

**Issue by 07souravkunda** [GameofSource-GFG/Web-Development#13]
Make a timeline to be added in the home page create a separate component and link it.

**Comment by Priyanshu-official** [comment]
I would like to Work assign to me!

**Comment by Priyanshu-official** [comment]
Thanks

**Comment by 07souravkunda** [comment]
@Priyanshu-official try to make you first commit within 48hrs.

**Comment by Tejaswika** [comment]
assign it to mee

**Comment by Priyanshu-official** [comment]
@07souravkunda ok

**Comment by Priyanshu-official** [comment]
Update: I am selecting the design, today before midnight I will try to make PR.
@07souravkunda 
one question 
 what I should give the name.
I am thinking to give Timeline

**Comment by 07souravkunda** [comment]
@Priyanshu-official Okay!

**Comment by Priyanshu-official** [comment]
@07souravkunda Pls let me know if it needs any changes.
Hope Hompage will have a similar color which I used.

**Comment by geekyaditya100** [comment]
@Priyanshu-official thank you for the contribution we have successfully merged your pull request.
You got 10 Points for the issue.
