### ISSUE TITLE
GOSW9-Navigation bar

### ISSUE THREAD

**Issue by 07souravkunda** [GameofSource-GFG/Web-Development#14]
Create a navigation bar in the home page. This navigation bar must be displayed at fixed and must be responsive in the site.

**Comment by sachinsom93** [comment]
Assign it to me

**Comment by somashrirastogi** [comment]
please assign this to me

**Comment by Shreya-art** [comment]
can you assign it to me??

**Comment by Shrayanshi** [comment]
Please assign it to me!

**Comment by Brighu-Raina** [comment]
Please, Assign it to me

**Comment by sachinsom93** [comment]
Can I work on this ?

**Comment by geekyaditya100** [comment]
@sachinsom93 is your older issue completed

**Comment by sachinsom93** [comment]
I made PR for that

**Comment by sachinsom93** [comment]
That's in review period

**Comment by Harshal0902** [comment]
Please assign this issue t me

**Comment by geekyaditya100** [comment]
@sachinsom93 kindly work on this issue

**Comment by amisha64** [comment]
Can you assign this to me?
