### ISSUE TITLE
GOSW10-Link the components to the navigation bar

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#29]
Link the separate modules from navigation bar to the specified components to display that component to the users.

**Comment by Priyanshu-official** [comment]
@nanda-mik I would like to work on this.
Pls Assign to me

**Comment by Priyanshu-official** [comment]
@nanda-mik Can I work On this Pls!

**Comment by nanda-mik** [comment]
@Priyanshu-official complete the issue no GOSW14 first which was assigned to you.

**Comment by Priyanshu-official** [comment]
@nanda-mik Ok

**Comment by Harshal0902** [comment]
@nanda-mik I have completed my earlier issue, can you please assign this issue to me

**Comment by Brighu-Raina** [comment]
Assign it to me i would like to work on this

**Comment by Priyanshu-official** [comment]
@nanda-mik I made PR for my Previous Issue i.e firebase auth Pls Review and need a guide for that also.
Can you Assign this one?

**Comment by nanda-mik** [comment]
@Priyanshu-official It was under review. You can go for the next hard level issue.

**Comment by nanda-mik** [comment]
@Brighu-Raina I am assigning this to you. Start working!!

**Comment by nanda-mik** [comment]
@Harshal0902 you pr is under review please wait a bit!

**Comment by geekyaditya100** [comment]
@Brighu-Raina Update your status

**Comment by geekyaditya100** [comment]
This issue is free now. Any one can contribute

**Comment by Priyanshu-official** [comment]
@pixan198 Assign me this  would like to work

**Comment by geekyaditya100** [comment]
you can work on this issue

**Comment by geekyaditya100** [comment]
@Priyanshu-official thank you for the contribution we have successfully merged your pr. YOu have recieved 15 Points (5 for extra effort). Keep it up.
