### ISSUE TITLE
GOSW11-Create a Login Page

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#30]
An interactive & fully responsive login form in React.

**Comment by Priyanshu-official** [comment]
@nanda-mik Assign me pls

**Comment by sachinsom93** [comment]
Can I work on this pls

**Comment by sachinsom93** [comment]
@nanda-mik can you plz assign me this ?

**Comment by nanda-mik** [comment]
@sachinsom93 work on this!!
