### ISSUE TITLE
GOSW14-Google Firebase Authentication setup

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#33]
Initialize and Setup the firebase authentication for login into the application.

**Comment by Priyanshu-official** [comment]
@nanda-mik I would Like to Work On this 
This Pls Assign me this One (Important this one Pls)

**Comment by nanda-mik** [comment]
@Priyanshu-official start working on this!!

**Comment by Priyanshu-official** [comment]
Thank you 💥

**Comment by Priyanshu-official** [comment]
@nanda-mik review my new pr I have made a component of firebase
