### ISSUE TITLE
GOSW15-Firebase 2 factor authentication setup

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#34]
Enable 2 factor authentication for users and make the validation request to the users

**Comment by Harshal0902** [comment]
@nanda-mik can you please assign this issue to me?

**Comment by geekyaditya100** [comment]
@Harshal0902 is other issue completed.

**Comment by Harshal0902** [comment]
@geekyaditya100 yes, I have done the required changes in my previous issue

**Comment by Priyanshu-official** [comment]
@geekyaditya100  Sorry to Interrupt but I am working on FA First #41  that's why waiting to review 
I will work on this too if get chance

**Comment by Harshal0902** [comment]
@geekyaditya100 can I work on this issue

**Comment by Harshal0902** [comment]
@geekyaditya100 can I finally work on this issue. My previous issue is merged.

**Comment by Harshal0902** [comment]
@nanda-mik @pixan198  can I work on this Issue.

**Comment by geekyaditya100** [comment]
@Harshal0902 thank you for the contribution. You have received 15 points for the contribution. We have merged your pr successfully.
