### ISSUE TITLE
GOSW16-Create an event Registration Form

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#35]
A form for registering for a new event by a campus lead having all the details like event name, location, schedule, eligibility, one poster section, organizing team details, sponsors details, etc.

**Comment by lakshayb121** [comment]
Assign me this

**Comment by sachinsom93** [comment]
@nanda-mik , Can I work on this Issue ?

**Comment by sachinsom93** [comment]
@nanda-mik, I have raised PR's for my previous issues ?

**Comment by geekyaditya100** [comment]
@sachinsom93 complete the previous issues and we will assign new to you later

**Comment by sachinsom93** [comment]
@geekyaditya100, I have already submitted PRs for my previous issues, do I need to wait till those are reviewed??

**Comment by sachinsom93** [comment]
@geekyaditya100, I have completed my previous issues, please assign it to me .

**Comment by nanda-mik** [comment]
@sachinsom93 first make the changes required in GOSW7.

**Comment by sachinsom93** [comment]
Can I work on this now @nanda-mik ?

**Comment by sachinsom93** [comment]
> Can I work on this now @nanda-mik ?

@nanda-mik ??

**Comment by ashish11chawda** [comment]
Hey @sachinsom93 Please start working on this issue
Sorry for the delay
