### ISSUE TITLE
GOSW17-Create an event table in database

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#39]
Storing the data from event registration form in the database.

**Comment by shivarajloni** [comment]
could you please elaborate it more specifically

**Comment by geekyaditya100** [comment]
We will provide credentials to the database. You need to push the data collected from registration form to the database.

**Comment by sachinsom93** [comment]
Which database will be used in this project mongo or sql ??

**Comment by nanda-mik** [comment]
@sachinsom93  Firestore is used as the database.

**Comment by sachinsom93** [comment]
Can I work on this @nanda-mik ?

**Comment by sachinsom93** [comment]
> We will provide credentials to the database. You need to push the data collected from registration form to the database
Kindly provide the credentials of database @geekyaditya100 .
