### ISSUE TITLE
GOSWB1- Contact Us Form Bug

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#50]
**Bugs which are to be resolved**

1. Validation for phone number field.
2. Message field shouldn't be infinite. Add a limit counter and show as red when it exceeds the limit.
3. Name field box dimensions(height/width) should match the other box dimensions.

**Always note this**
Use **comments** for better explanation of you code.

**Comment by sachinsom93** [comment]
Can I work on this @nanda-mik ?

**Comment by geekyaditya100** [comment]
@sachinsom93 is the other issue completed

**Comment by sachinsom93** [comment]
> @sachinsom93 is the other issue completed

I have raised a PR for that and that is also reviewed, i just need to do a small change in that @geekyaditya100

**Comment by geekyaditya100** [comment]
@sachinsom93 fine. Enjoy

**Comment by geekyaditya100** [comment]
@sachinsom93 thank you for the contribution. You have recieved 10 points for the contribution. We have merged your pr successfully. Keep up the spirit.
