### ISSUE TITLE
GOSW20- Loading the data from database to the events page.

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#52]
**Features to work on:**

1. Fetch all details about coming events and display it on the events page.

**Always note this:**

1. Use **comments** for better explanation of your code.
2. Try to resolve conflicts in the package.json files before submitting the PR.

**Comment by sachinsom93** [comment]
Kindly assign me @nanda-mik .

**Comment by nanda-mik** [comment]
@sachinsom93 work on this
