### ISSUE TITLE
GOSW21- Loading the data from database to the committee members page.

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#53]
**Features to work on:**

1. Fetch all details about coming events and display it on the committee members page.

**Always note this:**

1. Use **comments** for better explanation of your code.
2. Try to resolve conflicts in the package.json files before submitting the PR.

**Comment by sachinsom93** [comment]
@nanda-mik, @geekyaditya100 Kindly assign me, would like to work

**Comment by geekyaditya100** [comment]
@sachinsom93 you can work

**Comment by sachinsom93** [comment]
@nanda-mik , @geekyaditya100 please review it and let me know that i need do any improvments ?
