### ISSUE TITLE
GOSW22- Creation of contact us table in database

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#54]
**Features to work on:**

1. Create a table in db to save all the details from Contact us page.

**Always note this:**

1. Use **comments** for better explanation of your code.
2. Try to resolve conflicts in the package.json files before submitting the PR.

**Comment by 28avinash** [comment]
where to create a table?

**Comment by sachinsom93** [comment]
@nanda-mik , can I work on this issue simultaneously with GOSWB1 because I just need to do some changes in that component to insert contact us details to firestore ?
