### ISSUE TITLE
GOSW25- Track the number of unique users visiting the application.

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#56]
**Features to work on:**

1. track the no of unique visitors on the website.
2. explore packages to make it easier in react. 

**Always note this**
1. Use comments for better explanation of your code.
2. Try to resolve conflicts in the package.json files before submitting the PR.

**Comment by Priyanshu-official** [comment]
@nanda-mik if you want to track  how many people visit 
I can do that using react google Analytics it will show in the Dashboard of google analytics

**Comment by Harshal0902** [comment]
@nanda-mik please assign this issue to me.

**Comment by sachinsom93** [comment]
Can I work on this @nanda-mik ?

**Comment by sachinsom93** [comment]
I have completed all my previous issues, kindly assign me this task @nanda-mik .

**Comment by Harshal0902** [comment]
@AVS18 can I work on this issue?

**Comment by geekyaditya100** [comment]
@Harshal0902 you can work on the issue
