### ISSUE TITLE
GOSW31- Create a footer 

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#57]
**Features to work on:**

1. A responsive footer for the student chapter.
2. consisting of details such as navigation links, etc.

**Always note this**

1. Use **comments** for better explanation of your code.
2. Try to resolve conflicts in the package.json files before submitting the PR.

**Comment by Tejaswika** [comment]
Please assign this to me!!

**Comment by Priyanshu-official** [comment]
@nanda-mik Let me Work on this pls

**Comment by geekyaditya100** [comment]
We appreciate your enthusiasm and you can successfully work on this issue @Priyanshu-official

**Comment by geekyaditya100** [comment]
we expect the issue GOSW10 to be completed soon
