### ISSUE TITLE
GOSW32- Scroll to top button 

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#58]
**Features to work on:**

1. A nice button to appear when user scroll down.
2. Clicking it, should take the user to top of the page.

**Always note this**

1. Use **comments** for better explanation of your code.
2. Try to resolve conflicts in the package.json files before submitting the PR.

**Comment by Harshal0902** [comment]
@nanda-mik can i work on this issue

**Comment by geekyaditya100** [comment]
@Harshal0902 Complete GOSW3

**Comment by Harshal0902** [comment]
@geekyaditya100 I have made the changes as told by @nanda-mik in GOSW3 and he has merged the it

**Comment by geekyaditya100** [comment]
@Harshal0902 you can work now

**Comment by geekyaditya100** [comment]
We merged this issue and you have received 10 points for the contribution @Harshal0902
