### ISSUE TITLE
GOSW1- Make a UI for home section-GeeksforGeeks student Chapter Home page

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#6]
This will be the first page shown in the Webpage. Make it responsive with a rich user interactivity for the viewers. Create a component file containing the home page and export it as a default component.

**Comment by sachinsom93** [comment]
Assign me

**Comment by somashrirastogi** [comment]
assign me

**Comment by nanda-mik** [comment]
@sachinsom93 work on this issue!

**Comment by sachinsom93** [comment]
OK @nanda-mik, thanks for assigning
