### ISSUE TITLE
GOSW2-UI for about section-GeeksforGeeks student Chapter About page.

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#7]
This will be the second page shown after the application. Make it responsive with a rich user interactivity for the viewers. Make a separate component containing the code.

**Comment by Harshal0902** [comment]
Please assign this issue to me.

**Comment by somashrirastogi** [comment]
Please assign this to me

**Comment by sachinsom93** [comment]
Assign me plz

**Comment by Swastik1710** [comment]
Can you please assign this to me.

**Comment by Shreya-art** [comment]
can you assign it to me??

**Comment by nanda-mik** [comment]
@Harshal0902 work on this issue!

**Comment by Harshal0902** [comment]
@nanda-mik just a few clarification required :
1) Do I need to design nav-bar
2) Should it be exact copy of official geeksforgeeks about us page
3) Should it contain team members details

**Comment by Harshal0902** [comment]
And can I add some or your social-media icons?

**Comment by Harshal0902** [comment]
of*

**Comment by geekyaditya100** [comment]
@Harshal0902 Clarifications
1. Navigation bar is there in another issue, So don't design it.
2. No use your creativity and it should be good and mixing with other components in the design.
3. No It is again another issue.
I hope these clarified your doubts
4. Social media icons are also added in another issue. So Work on about us page and widespread your creativity

**Comment by Harshal0902** [comment]
@geekyaditya100 thank for clarification

**Comment by Priyanshu-official** [comment]
@Harshal0902 Have you done this!
if not let me know I will work on this

**Comment by Harshal0902** [comment]
@Priyanshu-official Yes, I have done this and requested for pull request
