### ISSUE TITLE
GOSW33- Newsletter subscription above footer area

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#71]
**Features to work on:**

1. A responsive component to accept the news letter subscription.

**Always note this**

1. Use **comments** for better explanation of your code.
2. Create new branch for each issues and make sure to pull the latest code from development branch.
2. Try to resolve conflicts in the files before submitting the PR.

**Comment by sachinsom93** [comment]
@nanda-mik , kindly assign me this, I have submitted PR's for my previous issues.

**Comment by Priyanshu-official** [comment]
@nanda-mik Assign me this pls completed issue and in review
  And also till then, I will try to fix Conflict
because of that, I was really waste so much time but learned a lot

**Comment by nanda-mik** [comment]
@sachinsom93 work on this!

**Comment by geekyaditya100** [comment]
@sachinsom93 thank you for the contribution. We have successfully merged the pull request. You have received 10 points for the contribution
