### ISSUE TITLE
GOSW34- Dark/Light Mode toggle Button 

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#73]
**Features to work on:**

1. Build a toggle that allows users to switch between light and dark modes.

**Always note this**

1. Use **comments** for better explanation of your code.
2. Create new branch for each issues and make sure to pull the latest code from development branch.
3. Try to resolve conflicts in the files before submitting the PR.

**Comment by Harshal0902** [comment]
@nanda-mik please assign this issue to me.

**Comment by nanda-mik** [comment]
@Harshal0902 work on this!
