### ISSUE TITLE
GOSW3-UI for Mission and Vision section-Geeksforgeeks Student chapter Mision and Vision section.

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#8]
This will be a separate component and must be mapped to the activity navigation bar.

**Comment by sachinsom93** [comment]
Assign me

**Comment by Neha62-lit** [comment]
Assign me

**Comment by Samdid** [comment]
Assign to me

**Comment by nanda-mik** [comment]
@Samdid work on this issue!

**Comment by Tejaswika** [comment]
assign it to mee

**Comment by Samdid** [comment]
> @Samdid work on this issue!

Ok, thanks.

**Comment by Samdid** [comment]
> @Samdid work on this issue!

Can you tell me, the time limit for this issue?

**Comment by nanda-mik** [comment]
@Samdid within 48hr you have to submit the PR.

**Comment by geekyaditya100** [comment]
This issue is opened now

**Comment by Swastik1710** [comment]
Can you assign it to me?

**Comment by sachinsom93** [comment]
Assign me please

**Comment by Priyanshu-official** [comment]
@geekyaditya100 Assign to me I like to work on this
if no one is doing

**Comment by geekyaditya100** [comment]
@Priyanshu-official you can work on this.

**Comment by geekyaditya100** [comment]
This issue is free. Anyone can contribute

**Comment by Aaliya7516** [comment]
I would like to try @geekyaditya100

**Comment by geekyaditya100** [comment]
@Aaliya7516  this should be completed soon. I am assigning this issue to you

**Comment by Harshal0902** [comment]
@geekyaditya100 Can I work on this Issue. I have completed my previous Issue and requested for pull request.

**Comment by nanda-mik** [comment]
@Harshal0902 start working on this and complete it soon.

**Comment by Harshal0902** [comment]
@nanda-mik Thank you, I will complete this issue as soon as possible.
