### ISSUE TITLE
GOSW4-UI for Committee Members section-GeeksforGeeks student chapter committee member details

### ISSUE THREAD

**Issue by nanda-mik** [GameofSource-GFG/Web-Development#9]
This will be a separate component and must mapped to the navigation.

**Comment by vaibhavarora102** [comment]
Hi Kindly assign me @nanada-milk

**Comment by nanda-mik** [comment]
@vaibhavarora102 work on this issue!

**Comment by vaibhavarora102** [comment]
@nanda-mik  can you pls tell the location of source file

**Comment by nanda-mik** [comment]
@vaibhavarora102  check inside the client folder.

**Comment by Tejaswika** [comment]
assign it to mee

**Comment by vaibhavarora102** [comment]
Hi @nanda-mik  currently got engaged in other work 
so, assign it to @Tejaswika

**Comment by Tejaswika** [comment]
@vaibhavarora102 thank you

**Comment by Tejaswika** [comment]
Should I start working on this??

**Comment by nanda-mik** [comment]
@Tejaswika work on this!

**Comment by Priyanshu-official** [comment]
@nanda-mik if this issue resolved so pls Close this
(opinion)

**Comment by geekyaditya100** [comment]
@Tejaswika thank you for the contribution. You have received 10 points for the contribution. Keep it up
